### ISSUE TITLE
填写无ISBN书籍问题

### ISSUE THREAD

**Issue by zhengzongsheng** [imlinhanchao/libraryII#7]
添加书籍中 ISBN为必选项
若出现无ISBN书籍（如 高校自制书籍）该如何操作
![mmexport1569861985503](https://user-images.githubusercontent.com/34943180/65899290-00fbdc80-e3e6-11e9-96d9-836a41ee1bf5.jpg)

**Comment by imlinhanchao** [comment]
已移除 ISBN 必填项。
